function showAlert() {
    alert("HALOO !!! NAMA SAYA AGIL IMAM ALHAFIZI BISA DI PANGGIL AGIL,ALAMAT SAYA JAMBI SEKARANG SAYA LAGI MENGERJAKAN TUGAS UCP 1,UNTUK MENGENAL SAYA LEBIH DETAIL KLIK BAR PROFILE DISANA TERDAPAT FOTO DAN BIODATA TENTANG SAYA DAN GAME YANG SAYA MAINKAN ");
}